[package]
name = "tecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.crossbeam-queue]
version = "0.3"

[dependencies.hashbrown]
version = "0.12"

